# Case Study with Pandas
- Filtering

In [1]:
#<img src=''>

In [2]:
lst = [1,2,3,4,5]

In [3]:
lst2 = []

In [4]:
for i in lst:
    lst2.append(i**2)

In [5]:
print(lst2)

[1, 4, 9, 16, 25]


In [6]:
lst3=[i**2 for i in lst]

In [7]:
print(lst3)

[1, 4, 9, 16, 25]


In [8]:
import pandas as pd

In [9]:
from pandas import Series, DataFrame

In [10]:
l1=Series(lst)

In [11]:
type(l1)

pandas.core.series.Series

In [12]:
l1+1

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [13]:
l2=[[1,2,3],[4,5,6],[7,8,9]]

In [14]:
import numpy as np

In [15]:
l3=np.array(l2)

In [16]:
type(l3)

numpy.ndarray

In [17]:
print(l3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(l3+2)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [19]:
import os

In [20]:
os.getcwd()

'C:\\Users\\lenovo\\Desktop\\AI Practical'

In [21]:
data=pd.read_csv("Store.csv", header=0,encoding='ANSI',sep=',') #encoding=latin,cp1252

In [22]:
data.head()

Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2013-152156   11/9/2013  11/12/2013    Second Class    CG-12520   
1       2  CA-2013-152156   11/9/2013  11/12/2013    Second Class    CG-12520   
2       3  CA-2013-138688   6/13/2013   6/17/2013    Second Class    DV-13045   
3       4  US-2012-108966  10/11/2012  10/18/2012  Standard Class    SO-20335   
4       5  US-2012-108966  10/11/2012  10/18/2012  Standard Class    SO-20335   

     Customer Name    Segment        Country             City    ...     \
0      Claire Gute   Consumer  United States        Henderson    ...      
1      Claire Gute   Consumer  United States        Henderson    ...      
2  Darrin Van Huff  Corporate  United States      Los Angeles    ...      
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale    ...      
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale    ...      

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

In [23]:
type(data)

pandas.core.frame.DataFrame

In [24]:
with open("Store.csv") as f:
    print(f)

<_io.TextIOWrapper name='Store.csv' mode='r' encoding='cp1252'>


In [25]:
data.tail()

Row ID        Order ID Order Date  Ship Date       Ship Mode  \
9989    9990  CA-2011-110422  1/22/2011  1/24/2011    Second Class   
9990    9991  CA-2014-121258  2/27/2014   3/4/2014  Standard Class   
9991    9992  CA-2014-121258  2/27/2014   3/4/2014  Standard Class   
9992    9993  CA-2014-121258  2/27/2014   3/4/2014  Standard Class   
9993    9994  CA-2014-119914   5/5/2014  5/10/2014    Second Class   

     Customer ID     Customer Name   Segment        Country         City  \
9989    TB-21400  Tom Boeckenhauer  Consumer  United States        Miami   
9990    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa   
9991    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa   
9992    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa   
9993    CC-12220      Chris Cortes  Consumer  United States  Westminster   

       ...    Postal Code  Region       Product ID         Category  \
9989   ...          33180   South  FUR-FU-10001889        Furniture   
9990   ...          92627    West  FUR-FU-10000747        Furniture   
9991   ...          92627    West  TEC-PH-10003645       Technology   
9992   ...          92627    West  OFF-PA-10004041  Office Supplies   
9993   ...          92683    West  OFF-AP-10002684  Office Supplies   

     Sub-Category                                       Product Name    Sales  \
9989  Furnishings                             Ultra Door Pull Handle   25.248   
9990  Furnishings  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.960   
9991       Phones                              Aastra 57i VoIP phone  258.576   
9992        Paper  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.600   
9993   Appliances  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.160   

      Quantity  Discount   Profit  
9989         3       0.2   4.1028  
9990         2       0.0  15.6332  
9991         2       0.2  19.3932  
9992         4       0.0  13.3200  
9993         2       0.0  72.9480  

[5 rows x 21 columns]

In [26]:
data.shape

(9994, 21)

In [27]:
data.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [77]:
print(data.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']


## Data Manupulation task :
- Filtering Data
- Selecting columns
- Sorting Data
- Adding new columns
- Deleting a column
- Groupby aggregation
- Handling Dates

In [29]:
print(data['City'].tolist())

['Henderson', 'Henderson', 'Los Angeles', 'Fort Lauderdale', 'Fort Lauderdale', 'Los Angeles', 'Los Angeles', 'Los Angeles', 'Los Angeles', 'Los Angeles', 'Los Angeles', 'Los Angeles', 'Concord', 'Seattle', 'Fort Worth', 'Fort Worth', 'Madison', 'West Jordan', 'San Francisco', 'San Francisco', 'San Francisco', 'Fremont', 'Fremont', 'Philadelphia', 'Orem', 'Los Angeles', 'Los Angeles', 'Philadelphia', 'Philadelphia', 'Philadelphia', 'Philadelphia', 'Philadelphia', 'Philadelphia', 'Philadelphia', 'Houston', 'Richardson', 'Richardson', 'Houston', 'Houston', 'Houston', 'Houston', 'Naperville', 'Los Angeles', 'Melbourne', 'Eagan', 'Eagan', 'Westland', 'Dover', 'Dover', 'New Albany', 'New Albany', 'New Albany', 'New Albany', 'New York City', 'New York City', 'Troy', 'Troy', 'Troy', 'Troy', 'Troy', 'Troy', 'Troy', 'Los Angeles', 'Los Angeles', 'Los Angeles', 'Los Angeles', 'Chicago', 'Gilbert', 'Gilbert', 'Springfield', 'New York City', 'Jackson', 'Memphis', 'Memphis', 'Memphis', 'Houston', '

In [30]:
len(data['City'].unique())

531

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
Row ID           9994 non-null int64
Order ID         9994 non-null object
Order Date       9994 non-null object
Ship Date        9994 non-null object
Ship Mode        9994 non-null object
Customer ID      9994 non-null object
Customer Name    9994 non-null object
Segment          9994 non-null object
Country          9994 non-null object
City             9994 non-null object
State            9994 non-null object
Postal Code      9994 non-null int64
Region           9994 non-null object
Product ID       9994 non-null object
Category         9994 non-null object
Sub-Category     9994 non-null object
Product Name     9994 non-null object
Sales            9994 non-null float64
Quantity         9994 non-null int64
Discount         9994 non-null float64
Profit           9994 non-null float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB


In [32]:
print(data.groupby(by=['City','Region']))

In [33]:
data[(data['Region']=='East')].shape[0] #0 for no.of rows and 1 for no. of columns

2848

In [34]:
data[(data['Region']=="East")]['Quantity'].sum() #total quantity sold in east region

10618

In [35]:
data.query("Region=='East'").sort_values('Sales',ascending=False)['Customer ID'].head()

2623    TA-21385
4190    HL-15040
4277    BS-11365
6425    CC-12370
6626    TB-21400
Name: Customer ID, dtype: object

In [36]:
data.query("Region=='East'").sort_values('Discount',ascending=False)['Customer ID'].head()

4823    CK-12205
8536    HD-14785
4711    JO-15280
4756    EB-13870
8886    BS-11590
Name: Customer ID, dtype: object

In [37]:
data.groupby('Region',as_index=False).agg({'Quantity':'mean'})

Region  Quantity
0  Central  3.779595
1     East  3.728230
2    South  3.832716
3     West  3.829535

In [38]:
data['Segment']

0          Consumer
1          Consumer
2         Corporate
3          Consumer
4          Consumer
5          Consumer
6          Consumer
7          Consumer
8          Consumer
9          Consumer
10         Consumer
11         Consumer
12         Consumer
13         Consumer
14      Home Office
15      Home Office
16         Consumer
17         Consumer
18         Consumer
19         Consumer
20         Consumer
21        Corporate
22        Corporate
23         Consumer
24         Consumer
25         Consumer
26         Consumer
27         Consumer
28         Consumer
29         Consumer
           ...     
9964      Corporate
9965      Corporate
9966      Corporate
9967       Consumer
9968       Consumer
9969       Consumer
9970    Home Office
9971    Home Office
9972       Consumer
9973    Home Office
9974    Home Office
9975    Home Office
9976    Home Office
9977    Home Office
9978    Home Office
9979    Home Office
9980       Consumer
9981       Consumer
9982       Consumer


In [39]:
data.groupby('Segment',as_index=False).agg({'Discount':'mean'})

Segment  Discount
0     Consumer  0.158141
1    Corporate  0.158228
2  Home Office  0.147128

In [40]:
data.groupby('Segment',as_index=False).agg({'Discount':'sum'})

Segment  Discount
0     Consumer    820.91
1    Corporate    477.85
2  Home Office    262.33

In [41]:
data.groupby('Segment',as_index=False).agg({'Discount':np.mean})

Segment  Discount
0     Consumer  0.158141
1    Corporate  0.158228
2  Home Office  0.147128

In [42]:
data.groupby('Segment',as_index=False).agg({'Discount':np.median})

Segment  Discount
0     Consumer       0.2
1    Corporate       0.2
2  Home Office       0.0

In [43]:
data['Country'].unique()

array(['United States'], dtype=object)

In [44]:
data.query("Segment=='Consumer'" and "Region=='South'")

Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2013-152156   11/9/2013  11/12/2013    Second Class   
1          2  CA-2013-152156   11/9/2013  11/12/2013    Second Class   
3          4  US-2012-108966  10/11/2012  10/18/2012  Standard Class   
4          5  US-2012-108966  10/11/2012  10/18/2012  Standard Class   
12        13  CA-2014-114412   4/16/2014   4/21/2014  Standard Class   
43        44  CA-2014-139619   9/20/2014   9/24/2014  Standard Class   
69        70  CA-2013-119823    6/5/2013    6/7/2013     First Class   
72        73  US-2012-134026   4/26/2012    5/2/2012  Standard Class   
73        74  US-2012-134026   4/26/2012    5/2/2012  Standard Class   
74        75  US-2012-134026   4/26/2012    5/2/2012  Standard Class   
79        80  CA-2013-127208   6/13/2013   6/16/2013     First Class   
80        81  CA-2013-127208   6/13/2013   6/16/2013     First Class   
83        84  CA-2012-149734    9/3/2012    9/8/2012  Standard Class   
85        86  CA-2014-140088   5/29/2014   5/31/2014    Second Class   
106      107  CA-2014-119004  11/24/2014  11/29/2014  Standard Class   
107      108  CA-2014-119004  11/24/2014  11/29/2014  Standard Class   
108      109  CA-2014-119004  11/24/2014  11/29/2014  Standard Class   
118      119  US-2012-136476    4/5/2012   4/10/2012  Standard Class   
182      183  CA-2011-158274  11/19/2011  11/24/2011    Second Class   
183      184  CA-2011-158274  11/19/2011  11/24/2011    Second Class   
184      185  CA-2011-158274  11/19/2011  11/24/2011    Second Class   
204      205  CA-2014-126382    6/4/2014    6/8/2014  Standard Class   
228      229  US-2012-145436   2/28/2012    3/4/2012  Standard Class   
229      230  US-2012-145436   2/28/2012    3/4/2012  Standard Class   
230      231  US-2011-156216   9/13/2011   9/17/2011  Standard Class   
231      232  US-2014-100930    4/8/2014   4/13/2014  Standard Class   
232      233  US-2014-100930    4/8/2014   4/13/2014  Standard Class   
233      234  US-2014-100930    4/8/2014   4/13/2014  Standard Class   
234      235  US-2014-100930    4/8/2014   4/13/2014  Standard Class   
235      236  US-2014-100930    4/8/2014   4/13/2014  Standard Class   
...      ...             ...         ...         ...             ...   
9758    9759  CA-2014-113705   3/28/2014   3/30/2014    Second Class   
9760    9761  CA-2014-159135   11/5/2014   11/9/2014  Standard Class   
9769    9770  CA-2013-123533  11/25/2013   12/1/2013  Standard Class   
9770    9771  CA-2013-123533  11/25/2013   12/1/2013  Standard Class   
9771    9772  CA-2013-123533  11/25/2013   12/1/2013  Standard Class   
9773    9774  CA-2013-160234   6/27/2013    7/4/2013  Standard Class   
9785    9786  CA-2012-155635    5/9/2012   5/13/2012  Standard Class   
9786    9787  US-2011-114377   11/5/2011   11/5/2011        Same Day   
9805    9806  CA-2013-136322  10/22/2013  10/27/2013  Standard Class   
9806    9807  CA-2013-136322  10/22/2013  10/27/2013  Standard Class   
9807    9808  CA-2014-107209   7/28/2014    8/2/2014    Second Class   
9815    9816  CA-2012-162201    6/8/2012   6/12/2012  Standard Class   
9816    9817  CA-2012-162201    6/8/2012   6/12/2012  Standard Class   
9817    9818  CA-2012-162201    6/8/2012   6/12/2012  Standard Class   
9818    9819  CA-2012-162201    6/8/2012   6/12/2012  Standard Class   
9819    9820  CA-2012-162201    6/8/2012   6/12/2012  Standard Class   
9820    9821  CA-2012-162201    6/8/2012   6/12/2012  Standard Class   
9821    9822  CA-2012-162201    6/8/2012   6/12/2012  Standard Class   
9829    9830  US-2014-152842   7/17/2014   7/24/2014  Standard Class   
9856    9857  CA-2011-120950   11/6/2011  11/11/2011  Standard Class   
9881    9882  CA-2011-153927   8/12/2011   8/13/2011     First Class   
9882    9883  CA-2011-153927   8/12/2011   8/13/2011     First Class   
9911    9912  US-2011-157231    4/5/2011    4/9/2011  Standard Class   
9960    9961  CA-2014-141446   9/17/2014   9/1

In [45]:
data[(data['Region']=='South') & (data['Segment']=='Consumer')]

Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2013-152156   11/9/2013  11/12/2013    Second Class   
1          2  CA-2013-152156   11/9/2013  11/12/2013    Second Class   
3          4  US-2012-108966  10/11/2012  10/18/2012  Standard Class   
4          5  US-2012-108966  10/11/2012  10/18/2012  Standard Class   
12        13  CA-2014-114412   4/16/2014   4/21/2014  Standard Class   
69        70  CA-2013-119823    6/5/2013    6/7/2013     First Class   
72        73  US-2012-134026   4/26/2012    5/2/2012  Standard Class   
73        74  US-2012-134026   4/26/2012    5/2/2012  Standard Class   
74        75  US-2012-134026   4/26/2012    5/2/2012  Standard Class   
85        86  CA-2014-140088   5/29/2014   5/31/2014    Second Class   
106      107  CA-2014-119004  11/24/2014  11/29/2014  Standard Class   
107      108  CA-2014-119004  11/24/2014  11/29/2014  Standard Class   
108      109  CA-2014-119004  11/24/2014  11/29/2014  Standard Class   
228      229  US-2012-145436   2/28/2012    3/4/2012  Standard Class   
229      230  US-2012-145436   2/28/2012    3/4/2012  Standard Class   
308      309  CA-2014-126774   4/16/2014   4/18/2014     First Class   
384      385  US-2012-168935  11/27/2012   12/2/2012  Standard Class   
385      386  US-2012-168935  11/27/2012   12/2/2012  Standard Class   
402      403  CA-2011-113166  12/24/2011  12/26/2011     First Class   
424      425  CA-2014-155705   8/22/2014   8/24/2014    Second Class   
434      435  US-2011-150574  12/19/2011  12/25/2011  Standard Class   
435      436  US-2011-150574  12/19/2011  12/25/2011  Standard Class   
494      495  US-2013-120929   3/19/2013   3/22/2013    Second Class   
495      496  CA-2012-134782  12/27/2012  12/31/2012  Standard Class   
506      507  CA-2012-145352   3/16/2012   3/22/2012  Standard Class   
507      508  CA-2012-145352   3/16/2012   3/22/2012  Standard Class   
508      509  CA-2012-145352   3/16/2012   3/22/2012  Standard Class   
509      510  CA-2012-145352   3/16/2012   3/22/2012  Standard Class   
533      534  CA-2013-168753   5/30/2013    6/2/2013    Second Class   
534      535  CA-2013-168753   5/30/2013    6/2/2013    Second Class   
...      ...             ...         ...         ...             ...   
9382    9383  CA-2011-154158  12/23/2011  12/27/2011    Second Class   
9383    9384  CA-2011-154158  12/23/2011  12/27/2011    Second Class   
9400    9401  CA-2012-167696   9/16/2012   9/21/2012  Standard Class   
9565    9566  CA-2011-130428   3/31/2011   3/31/2011        Same Day   
9566    9567  CA-2011-130428   3/31/2011   3/31/2011        Same Day   
9567    9568  CA-2011-130428   3/31/2011   3/31/2011        Same Day   
9601    9602  CA-2013-117604    9/5/2013   9/10/2013  Standard Class   
9602    9603  CA-2011-130155   5/19/2011   5/22/2011     First Class   
9604    9605  CA-2012-138625   11/2/2012   11/5/2012     First Class   
9611    9612  CA-2014-144365  10/25/2014  10/31/2014  Standard Class   
9639    9640  CA-2012-116638   1/28/2012   1/31/2012    Second Class   
9669    9670  CA-2014-145275    4/3/2014    4/7/2014  Standard Class   
9688    9689  US-2014-135986   6/21/2014   6/28/2014  Standard Class   
9689    9690  US-2014-135986   6/21/2014   6/28/2014  Standard Class   
9753    9754  CA-2014-113705   3/28/2014   3/30/2014    Second Class   
9754    9755  CA-2014-113705   3/28/2014   3/30/2014    Second Class   
9755    9756  CA-2014-113705   3/28/2014   3/30/2014    Second Class   
9756    9757  CA-2014-113705   3/28/2014   3/30/2014    Second Class   
9757    9758  CA-2014-113705   3/28/2014   3/30/2014    Second Class   
9758    9759  CA-2014-113705   3/28/2014   3/30/2014    Second Class   
9773    9774  CA-2013-160234   6/27/2013    7/4/2013  Standard Class   
9785    9786  CA-2012-155635    5/9/2012   5/13/2012  Standard Class   
9786    9787  US-2011-114377   11/5/2011   11/5/2011        Same Day   
9807    9808  CA-2014-107209   7/28/2014    8/

In [46]:
data[(data['Region']=='South') & (data['Segment']=='Consumer') & (data['Customer ID']=='CG-12520')]

Row ID        Order ID Order Date   Ship Date     Ship Mode Customer ID  \
0       1  CA-2013-152156  11/9/2013  11/12/2013  Second Class    CG-12520   
1       2  CA-2013-152156  11/9/2013  11/12/2013  Second Class    CG-12520   

  Customer Name   Segment        Country       City    ...    Postal Code  \
0   Claire Gute  Consumer  United States  Henderson    ...          42420   
1   Claire Gute  Consumer  United States  Henderson    ...          42420   

   Region       Product ID   Category Sub-Category  \
0   South  FUR-BO-10001798  Furniture    Bookcases   
1   South  FUR-CH-10000454  Furniture       Chairs   

                                        Product Name   Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.96         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.94         3   

   Discount    Profit  
0       0.0   41.9136  
1       0.0  219.5820  

[2 rows x 21 columns]

In [47]:
data[(data['Region']=='South')].agg({'Discount':np.mean})

Discount    0.147253
dtype: float64

In [48]:
data[(data['Region']=='East')].agg({'Discount':np.mean})

Discount    0.145365
dtype: float64

In [49]:
data[(data['Region']=='West')].agg({'Discount':np.mean})

Discount    0.109335
dtype: float64

#### To rename the column

In [50]:
data.groupby('Region',as_index=False).agg({'Discount':np.mean}).rename(columns={'Discount':'Average Discount'})

Region  Average Discount
0  Central          0.240353
1     East          0.145365
2    South          0.147253
3     West          0.109335

In [51]:
data.groupby('Region',as_index=False).agg({'Discount':np.mean}).rename(columns={'Discount':'Average Discount'}).sort_values('Average Discount')

Region  Average Discount
3     West          0.109335
1     East          0.145365
2    South          0.147253
0  Central          0.240353

In [52]:
data.groupby('Segment',as_index=False).agg({'Profit':max}).sort_values('Profit')

Segment     Profit
2  Home Office  3919.9888
0     Consumer  6719.9808
1    Corporate  8399.9760

In [53]:
#### 

In [54]:
data.groupby('Category',as_index=False).agg({'Profit':max})

Category    Profit
0        Furniture  1013.127
1  Office Supplies  4946.370
2       Technology  8399.976

In [55]:
data['Sales']

0        261.9600
1        731.9400
2         14.6200
3        957.5775
4         22.3680
5         48.8600
6          7.2800
7        907.1520
8         18.5040
9        114.9000
10      1706.1840
11       911.4240
12        15.5520
13       407.9760
14        68.8100
15         2.5440
16       665.8800
17        55.5000
18         8.5600
19       213.4800
20        22.7200
21        19.4600
22        60.3400
23        71.3720
24      1044.6300
25        11.6480
26        90.5700
27      3083.4300
28         9.6180
29       124.2000
          ...    
9964      13.4000
9965       4.9800
9966     109.6900
9967      40.2000
9968     735.9800
9969      22.7500
9970     119.5600
9971     140.7500
9972      99.5680
9973     271.9600
9974      18.6900
9975      13.3600
9976     249.5840
9977      13.8600
9978      13.3760
9979     437.4720
9980      85.9800
9981      16.5200
9982      35.5600
9983      97.9800
9984      31.5000
9985      55.6000
9986      36.2400
9987      79.9900
9988     2

#### To add a column (feature) into table

In [56]:
data['Avg_Sale']=(data['Sales'])/(data['Sales'].mean())

In [57]:
data['Avg_Sale'].head()

0    1.139660
1    3.184314
2    0.063604
3    4.165952
4    0.097312
Name: Avg_Sale, dtype: float64

#### To drop a table

In [58]:
data.drop(['Avg_Sale'],axis=1,inplace=True) #inplace=True means column will be drop from table

In [59]:
data.head()

Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2013-152156   11/9/2013  11/12/2013    Second Class    CG-12520   
1       2  CA-2013-152156   11/9/2013  11/12/2013    Second Class    CG-12520   
2       3  CA-2013-138688   6/13/2013   6/17/2013    Second Class    DV-13045   
3       4  US-2012-108966  10/11/2012  10/18/2012  Standard Class    SO-20335   
4       5  US-2012-108966  10/11/2012  10/18/2012  Standard Class    SO-20335   

     Customer Name    Segment        Country             City    ...     \
0      Claire Gute   Consumer  United States        Henderson    ...      
1      Claire Gute   Consumer  United States        Henderson    ...      
2  Darrin Van Huff  Corporate  United States      Los Angeles    ...      
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale    ...      
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale    ...      

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

## Multilevel Indexing

In [60]:
data.groupby("Category")[['Sales','Profit']].agg(['max','mean'])

Sales                Profit           
                       max        mean       max       mean
Category                                                   
Furniture         4416.174  349.834887  1013.127   8.699327
Office Supplies   9892.740  119.324101  4946.370  20.327050
Technology       22638.480  452.709276  8399.976  78.752002

#### What is the total Sales, Quantity, Discount and Profit across Total US

In [61]:
def get_sum(x):
    return np.sum(x)

In [62]:
data[['Sales','Quantity','Discount','Profit']].apply(get_sum,axis=0)   #apply funct apply the given funct to all the column

Sales       2.297201e+06
Quantity    3.787300e+04
Discount    1.561090e+03
Profit      2.863970e+05
dtype: float64

In [74]:
Profit_flat= (data['Profit']>29).map({True:'Above 29',False:'Below 29'})

In [75]:
data['Profit'].mean()

28.656896307784802

In [76]:
Profit_flat

0       Above 29
1       Above 29
2       Below 29
3       Below 29
4       Below 29
5       Below 29
6       Below 29
7       Above 29
8       Below 29
9       Above 29
10      Above 29
11      Above 29
12      Below 29
13      Above 29
14      Below 29
15      Below 29
16      Below 29
17      Below 29
18      Below 29
19      Below 29
20      Below 29
21      Below 29
22      Below 29
23      Below 29
24      Above 29
25      Below 29
26      Below 29
27      Below 29
28      Below 29
29      Below 29
          ...   
9964    Below 29
9965    Below 29
9966    Above 29
9967    Below 29
9968    Above 29
9969    Below 29
9970    Above 29
9971    Above 29
9972    Above 29
9973    Below 29
9974    Below 29
9975    Below 29
9976    Above 29
9977    Below 29
9978    Below 29
9979    Above 29
9980    Below 29
9981    Below 29
9982    Below 29
9983    Below 29
9984    Below 29
9985    Below 29
9986    Below 29
9987    Below 29
9988    Above 29
9989    Below 29
9990    Below 29
9991    Below 

#### Find how much time it take to deliver a order

In [78]:
data['Order Date'] = pd.to_datetime(data['Order Date'])

In [80]:
data['Ship Date'] = pd.to_datetime(data['Ship Date'])

In [82]:
data['delivery_days']=data['Ship Date']-data['Order Date']

In [83]:
data['delivery_days']

0      3 days
1      3 days
2      4 days
3      7 days
4      7 days
5      5 days
6      5 days
7      5 days
8      5 days
9      5 days
10     5 days
11     5 days
12     5 days
13     5 days
14     4 days
15     4 days
16     7 days
17     2 days
18     5 days
19     5 days
20     5 days
21     4 days
22     4 days
23     2 days
24     5 days
25     4 days
26     4 days
27     4 days
28     4 days
29     4 days
        ...  
9964   5 days
9965   5 days
9966   5 days
9967   6 days
9968   6 days
9969   6 days
9970   4 days
9971   4 days
9972   6 days
9973   4 days
9974   4 days
9975   4 days
9976   4 days
9977   4 days
9978   4 days
9979   4 days
9980   3 days
9981   3 days
9982   6 days
9983   6 days
9984   6 days
9985   6 days
9986   4 days
9987   4 days
9988   4 days
9989   2 days
9990   5 days
9991   5 days
9992   5 days
9993   5 days
Name: delivery_days, Length: 9994, dtype: timedelta64[ns]

In [85]:
data['delivery_days'].dtype

dtype('<m8[ns]')

#### How many time has it taken more than 5 days from placing an order to shipping ?

In [98]:
(data['delivery_days'] > '5 days').sum()

1822

In [99]:
data[(data['delivery_days'] > '5 days')].shape[0]

1822

In [102]:
a=((data['delivery_days'] > '5 days').sum()/(data.shape[0]))*100

In [103]:
a

18.230938563137883

#### Categories exceeding shipment by 5 days

In [109]:
data[(data['delivery_days'] > '5 days')].groupby("Category").agg({'Category':np.size})

Category
Category                 
Furniture             365
Office Supplies      1131
Technology            326