In [1]:
import numpy as np
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('winequality-red.csv',header=0,encoding='ANSI',sep=';')

In [3]:
data.head(3)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5

In [4]:
data.shape

(1599, 12)

In [5]:
print(data.columns.tolist())

['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']


## 1.Standardscaler                     
###  z=(x-u)/s               
###  where u:mean  s:standard deviation

In [6]:
x=np.array([[-400],[-100],[0],[100],[400]])

In [7]:
import sklearn.preprocessing as preprocessing

In [8]:
stdscaler = preprocessing.StandardScaler()

In [9]:
stdscaler.fit_transform(x)

array([[-1.53392998],
       [-0.38348249],
       [ 0.        ],
       [ 0.38348249],
       [ 1.53392998]])

In [10]:
x

array([[-400],
       [-100],
       [   0],
       [ 100],
       [ 400]])

## Cross-verification

In [11]:
np.mean(x)

0.0

In [12]:
np.std(x)

260.76809620810593

In [13]:
(x[0]-(np.mean(x)))/np.std(x)

array([-1.53392998])

In [27]:
(x[3]-(np.mean(x)))/np.std(x)

array([0.38348249])

In [28]:
data1

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [29]:
stdscaler.fit_transform(data1)

array([[-0.52835961,  0.96187667, -1.39147228, ..., -0.57920652,
        -0.96024611, -0.78782264],
       [-0.29854743,  1.96744245, -1.39147228, ...,  0.1289504 ,
        -0.58477711, -0.78782264],
       [-0.29854743,  1.29706527, -1.18607043, ..., -0.04808883,
        -0.58477711, -0.78782264],
       ...,
       [-1.1603431 , -0.09955388, -0.72391627, ...,  0.54204194,
         0.54162988,  0.45084835],
       [-1.39015528,  0.65462046, -0.77526673, ...,  0.30598963,
        -0.20930812, -0.78782264],
       [-1.33270223, -1.21684919,  1.02199944, ...,  0.01092425,
         0.54162988,  0.45084835]])

## 2) MinMaxScaler
###   formulae:(x-x_min)/(x_max-x_min)

In [30]:
minmax = preprocessing.MinMaxScaler(feature_range=(0,1))

In [31]:
x=np.array([[-400],[-100],[0],[100],[400]])

In [32]:
minmax.fit_transform(x)

array([[0.   ],
       [0.375],
       [0.5  ],
       [0.625],
       [1.   ]])

## Cross-verification

In [33]:
(x[0]-np.min(x))/(np.max(x)-np.min(x))

array([0.])

In [34]:
(x[3]-np.min(x))/(np.max(x)-np.min(x))

array([0.625])

In [35]:
x3=np.array([[1,2,3],[4,5,6],[7,8,9]])
x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
minmax.fit_transform(x3)

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

In [37]:
(x3[0:3,]-np.min(x3[0:3,]))/(np.max(x3[0:3,])-np.min(x3[0:3,]))

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [38]:
minmax.fit_transform(data1)

array([[0.24778761, 0.39726027, 0.        , ..., 0.13772455, 0.15384615,
        0.4       ],
       [0.28318584, 0.52054795, 0.        , ..., 0.20958084, 0.21538462,
        0.4       ],
       [0.28318584, 0.43835616, 0.04      , ..., 0.19161677, 0.21538462,
        0.4       ],
       ...,
       [0.15044248, 0.26712329, 0.13      , ..., 0.25149701, 0.4       ,
        0.6       ],
       [0.11504425, 0.35958904, 0.12      , ..., 0.22754491, 0.27692308,
        0.4       ],
       [0.12389381, 0.13013699, 0.47      , ..., 0.19760479, 0.4       ,
        0.6       ]])

## 3)MaxAbsScaler 
### x/max(abs(x))

In [39]:
maxabs=preprocessing.MaxAbsScaler()

In [40]:
x=np.array([[-400],[-100],[0],[100],[400]])

In [41]:
maxabs.fit_transform(x)

array([[-1.  ],
       [-0.25],
       [ 0.  ],
       [ 0.25],
       [ 1.  ]])

In [44]:
x3=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [45]:
maxabs.fit_transform(x3)

array([[0.14285714, 0.25      , 0.33333333],
       [0.57142857, 0.625     , 0.66666667],
       [1.        , 1.        , 1.        ]])

## Cross-verification

In [42]:
x[1]/max(abs(x))

array([-0.25])

In [43]:
x[0]/max(abs(x))

array([-1.])

In [52]:
5/(np.max(abs(x3[:,1])))

0.625

In [51]:
np.max(abs(x3[:,1]))

8

In [50]:
max(abs(x))

array([400])

## 4) Normalizer
###  x_normalizer = x/max(x)

In [72]:
normalizer = preprocessing.Normalizer(norm='max')

In [73]:
x=np.array([[-400],[-100],[0],[100],[400]])

In [74]:
normalizer.fit_transform(x)

array([[1.],
       [1.],
       [0.],
       [1.],
       [1.]])

In [75]:
x3=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [76]:
normalizer.fit_transform(x3)

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

## Cross-verification

In [65]:
x[4]/max(x)

array([1.])

In [80]:
x3[1][1]/max(x3[1,:])

0.8333333333333334

## 3-b)l1 Normalizer

### x_normalized = x/sum(x)

In [82]:
l1_normalizer= preprocessing.Normalizer(norm='l1')

In [83]:
x=np.array([[-400],[-100],[0],[100],[400]])

In [84]:
l1_normalizer.fit_transform(x)

array([[-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 1.]])

In [85]:
x3=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [86]:
l1_normalizer.fit_transform(x3)

array([[0.16666667, 0.33333333, 0.5       ],
       [0.26666667, 0.33333333, 0.4       ],
       [0.29166667, 0.33333333, 0.375     ]])

## Cross-verification

In [92]:
x3[1][1]/sum(x3[1,:])

0.3333333333333333

In [89]:
x3[0][0]/sum(x3[0,:])

0.16666666666666666

In [90]:
x3[1][0]/sum(x3[1,:])

0.26666666666666666

## 3-c)l2-normalizer

### x_normailzed = x/sqrt(sum((i**2) for i in X))

In [94]:
normalizer_l2=preprocessing.Normalizer(norm='l2')

In [95]:
normalizer_l2.fit_transform(x)

array([[-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 1.]])

In [96]:
normalizer_l2.fit_transform(x3)

array([[0.26726124, 0.53452248, 0.80178373],
       [0.45584231, 0.56980288, 0.68376346],
       [0.50257071, 0.57436653, 0.64616234]])

## Cross-verification

In [116]:
x3[1][1]/np.sqrt(sum((i**2) for i in x3[1,:]))

0.5698028822981898

In [117]:
x[0]/np.sqrt(sum((i**2) for i in x))

array([-0.68599434])

## 4)Binarizer

In [118]:
binarizer = preprocessing.Binarizer(threshold=0.5)

In [120]:
binarizer.fit_transform(x)

array([[0],
       [0],
       [0],
       [1],
       [1]])

In [121]:
binarizer.fit_transform(x3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## Cross-verification

#### value greater than 0.5 = 1 &value less than 0.5 = 0

### Explanation for fit transform

In [16]:
x2=np.array([[1,2,3],[4,5,6],[7,8,9]])
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
stdscaler.fit_transform(x2)

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

In [18]:
s=stdscaler.fit(x2)

In [19]:
s.mean_

array([4., 5., 6.])

In [20]:
np.std(x2[:,0])

2.449489742783178

In [21]:
np.std(x2[:,1])

2.449489742783178

In [22]:
np.std(x2[:,2])      #<img src=' '>  Standard deviation formula

2.449489742783178

In [23]:
x3=np.array([[10,10,12],[15,14,15],[18,17,18]])

In [24]:
s.transform(x3)

array([[2.44948974, 2.04124145, 2.44948974],
       [4.4907312 , 3.67423461, 3.67423461],
       [5.71547607, 4.89897949, 4.89897949]])

In [25]:
data1=data.values

In [26]:
data1

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])